name: Continuous integration

on: [push, pull_request]

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Verify dependencies
      run: cd serverless_go && go mod verify

    - name: Build
      run: cd serverless_go && make build

    - name: Run go vet
      run: cd serverless_go && go vet ./...

    - name: Install golint
      run: cd serverless_go && go install golang.org/x/lint/golint@latest

    - name: Run golint
      run: cd serverless_go && golint ./...

    - name: Run tests
      run: cd serverless_go && go test ./...