name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Build 
        run: cd grace && go mod tidy && go build -v ./...

      - name: Test
        run: cd grace && go test -v ./...

      - name: Generate tag
        id: generate-tag
        run: echo "::set-output name=tag::$(git describe --abbrev=0 --tags)"
  
      - name: Build Docker
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_TAG: ${{ steps.generate-tag.outputs.tag }}
        run: |
          cd grace &&
          docker build -t my-golang-app . &&
          mkdir -p ~/.docker
          echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(echo -n "${DOCKER_USERNAME}:${DOCKER_PASSWORD}" | base64 -w 0)\"}}}" > ~/.docker/config.json
          docker tag my-golang-app:latest ${DOCKER_USERNAME}/rd:v${DOCKER_TAG}
          docker push ${DOCKER_USERNAME}/rd:v${DOCKER_TAG}