name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Build 
        run: cd grace && go mod tidy && go build -v ./...

      - name: Test
        run: cd grace && go test -v ./...

      - name: Get Git commit hash
        id: get-commit-hash
        run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"

      - name: Build Docker
        env:
          DOCKER_TAG: ${{ steps.get-commit-hash.outputs.commit_hash }}
        run: 
         cd grace 
         docker build -t my-golang-app .
         docker login -p ${{ secrets.DOCKERHUB_PASSWORD }} -u ${{ secrets.DOCKERHUB_USERNAME }} 
         docker tag my-golang-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/rd:latest 
         docker tag my-golang-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/rd:${DOCKER_TAG} 
         docker push ${{ secrets.DOCKERHUB_USERNAME }}/rd:latest 
         docker push ${{ secrets.DOCKERHUB_USERNAME }}/rd:${DOCKER_TAG}

 